---
abstract: 'Name your fields...'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  Catalyst::Test: '0'
  Test::Most: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.041, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-ActionRole-NamedFields
requires:
  Catalyst: '5.90060'
  Moose::Role: '2.0602'
resources:
  bugtracker: https://github.com/jjn1056/Catalyst-ActionRole-NamedFields/issues
  homepage: https://github.com/jjn1056/Catalyst-ActionRole-NamedFields
  repository: https://github.com/jjn1056/Catalyst-ActionRole-NamedFields.git
version: '0.001'
